### ISSUE TITLE
Theme suggestion

### ISSUE THREAD

**Issue by xji3** [aki-nishimura/aki-nishimura.github.io#1]
Aki, congratulations on your github page.  You probably already know about jekyll themes.  I just want to make a recommendation about the theme "Minimal Mistakes" which seems pretty flexible.  You may check it out here: https://mademistakes.com/work/minimal-mistakes-jekyll-theme/.

**Comment by aki-nishimura** [comment]
Thanks, I am still learning Jekyll and testing it locally.
